services:

  api:
    container_name: realtime-api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: src/Api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: realtime
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:    
    container_name: realtime-db
    image: postgres:latest        
    environment:
      POSTGRES_DB: realtime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/realtime-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

#  ui:
#    container_name: realtime-ui
#    image: ${DOCKER_REGISTRY-}ui
#    build:
#      context: src/Ui
#      dockerfile: Dockerfile
#    ports:
#      - 4200:80
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    depends_on:
#      - api